name: Security Validation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      elasticsearch:
        image: elasticsearch:8.9.1
        ports: ["9200:9200"]
        env:
          discovery.type: single-node
          xpack.security.enabled: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r src/ -f json -o bandit_results.json
          
      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit_results.json

          